# Generated by Django 4.2.2 on 2023-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardpostlike',
            unique_together=set(),
        ),
    ]
