# Generated by Django 4.2.2 on 2023-08-18 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_alter_boardpostlike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardpostlike',
            unique_together={('post', 'user')},
        ),
    ]
